# Generated by Django 4.0.4 on 2022-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('custom_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
